@WordSoulApi_HostAddress = https://localhost:7272

GET {{WordSoulApi_HostAddress}}/api/Vocabulary
Accept: application/json

###

POST {{WordSoulApi_HostAddress}}/api/Vocabulary
Content-Type: application/json

{
    "word": "Hello",
    "definition": "Xin chào",
    "example": "Hello, how are you?"
}

###