// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WordSoul.Infrastructure.Persistence;

#nullable disable

namespace WordSoul.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WordSoulDbContext))]
    [Migration("20260318163807_AddGymLeaderSystem")]
    partial class AddGymLeaderSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WordSoul.Domain.Entities.Achievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConditionType")
                        .HasColumnType("int");

                    b.Property<int>("ConditionValue")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RewardItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("Achievements");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            ConditionType = 4,
                            ConditionValue = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Defeated Norm, Guardian of Daily Life",
                            Name = "Boulder Badge",
                            RewardItemId = 0
                        },
                        new
                        {
                            Id = 102,
                            ConditionType = 4,
                            ConditionValue = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Defeated Flora, Guardian of Nature",
                            Name = "Leaf Badge",
                            RewardItemId = 0
                        },
                        new
                        {
                            Id = 103,
                            ConditionType = 4,
                            ConditionValue = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Defeated Hail, Guardian of Weather",
                            Name = "Frost Badge",
                            RewardItemId = 0
                        },
                        new
                        {
                            Id = 104,
                            ConditionType = 4,
                            ConditionValue = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Defeated Marina, Guardian of Food",
                            Name = "Tide Badge",
                            RewardItemId = 0
                        },
                        new
                        {
                            Id = 105,
                            ConditionType = 4,
                            ConditionValue = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Defeated Volt, Guardian of Technology",
                            Name = "Spark Badge",
                            RewardItemId = 0
                        },
                        new
                        {
                            Id = 106,
                            ConditionType = 4,
                            ConditionValue = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Defeated Aero, Guardian of Travel",
                            Name = "Wing Badge",
                            RewardItemId = 0
                        },
                        new
                        {
                            Id = 107,
                            ConditionType = 4,
                            ConditionValue = 7,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Defeated Lumi, Guardian of Health",
                            Name = "Glow Badge",
                            RewardItemId = 0
                        },
                        new
                        {
                            Id = 108,
                            ConditionType = 4,
                            ConditionValue = 8,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Defeated Brawl, Guardian of Sports",
                            Name = "Iron Badge",
                            RewardItemId = 0
                        });
                });

            modelBuilder.Entity("WordSoul.Domain.Entities.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Details")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("WordSoul.Domain.Entities.AnswerRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("HintCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("LearningSessionId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionType")
                        .HasColumnType("int");

                    b.Property<double>("ResponseTimeSeconds")
                        .HasColumnType("float");

                    b.Property<int>("VocabularyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VocabularyId");

                    b.HasIndex("LearningSessionId", "VocabularyId", "QuestionType");

                    b.ToTable("AnswerRecords");
                });

            modelBuilder.Entity("WordSoul.Domain.Entities.BattleAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BattleSessionId")
                        .HasColumnType("int");

                    b.Property<string>("ChallengerAnswer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ChallengerAnsweredMs")
                        .HasColumnType("int");

                    b.Property<bool>("ChallengerIsCorrect")
                        .HasColumnType("bit");

                    b.Property<string>("OpponentAnswer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OpponentAnsweredMs")
                        .HasColumnType("int");

                    b.Property<bool>("OpponentIsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionOrder")
                        .HasColumnType("int");

                    b.Property<int>("VocabularyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BattleSessionId");

                    b.HasIndex("VocabularyId");

                    b.ToTable("BattleAnswers");
                });

            modelBuilder.Entity("WordSoul.Domain.Entities.BattleSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChallengerCorrect")
                        .HasColumnType("int");

                    b.Property<int>("ChallengerUserId")
                        .HasColumnType("int");

                    b.Property<bool?>("ChallengerWon")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GymLeaderId")
                        .HasColumnType("int");

                    b.Property<int>("OpponentCorrect")
                        .HasColumnType("int");

                    b.Property<int?>("OpponentUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GymLeaderId");

                    b.HasIndex("OpponentUserId");

                    b.HasIndex("ChallengerUserId", "Status");

                    b.ToTable("BattleSessions");
                });

            modelBuilder.Entity("WordSoul.Domain.Entities.DailyQuest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("QuestType")
                        .HasColumnType("int");

                    b.Property<int?>("RewardReferenceId")
                        .HasColumnType("int");

                    b.Property<int>("RewardType")
                        .HasColumnType("int");

                    b.Property<int>("RewardValue")
                        .HasColumnType("int");

                    b.Property<int>("TargetValue")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("DailyQuests");
                });

            modelBuilder.Entity("WordSoul.Domain.Entities.GymLeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("BadgeAchievementId")
                        .HasColumnType("int");

                    b.Property<string>("BadgeImageUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("BadgeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CooldownHours")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("GymOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PassRatePercent")
                        .HasColumnType("int");

                    b.Property<int>("QuestionCount")
                        .HasColumnType("int");

                    b.Property<int>("RequiredCefrLevel")
                        .HasColumnType("int");

                    b.Property<string>("RequiredMemoryState")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Theme")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("VocabThreshold")
                        .HasColumnType("int");

                    b.Property<int>("XpReward")
                        .HasColumnType("int");

                    b.Property<int>("XpThreshold")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BadgeAchievementId");

                    b.ToTable("GymLeaders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BadgeAchievementId = 101,
                            BadgeName = "Boulder Badge",
                            CooldownHours = 12,
                            Description = "Norm greets every newcomer with a warm smile. Her words are simple, but mastering them is the foundation of your journey.",
                            GymOrder = 1,
                            Name = "Norm",
                            PassRatePercent = 80,
                            QuestionCount = 15,
                            RequiredCefrLevel = 0,
                            RequiredMemoryState = "Learning",
                            Theme = 0,
                            Title = "Guardian of Daily Life",
                            VocabThreshold = 15,
                            XpReward = 150,
                            XpThreshold = 300
                        },
                        new
                        {
                            Id = 2,
                            BadgeAchievementId = 102,
                            BadgeName = "Leaf Badge",
                            CooldownHours = 12,
                            Description = "Flora speaks in the language of forests and living things. She rewards those who have truly internalized the world around them.",
                            GymOrder = 2,
                            Name = "Flora",
                            PassRatePercent = 80,
                            QuestionCount = 15,
                            RequiredCefrLevel = 0,
                            RequiredMemoryState = "Review",
                            Theme = 1,
                            Title = "Guardian of Nature",
                            VocabThreshold = 15,
                            XpReward = 200,
                            XpThreshold = 600
                        },
                        new
                        {
                            Id = 3,
                            BadgeAchievementId = 103,
                            BadgeName = "Frost Badge",
                            CooldownHours = 12,
                            Description = "Hail's temperament shifts like the wind. Only those who can describe the sky in all its moods can earn her trust.",
                            GymOrder = 3,
                            Name = "Hail",
                            PassRatePercent = 80,
                            QuestionCount = 15,
                            RequiredCefrLevel = 1,
                            RequiredMemoryState = "Learning",
                            Theme = 2,
                            Title = "Guardian of Weather",
                            VocabThreshold = 20,
                            XpReward = 250,
                            XpThreshold = 1000
                        },
                        new
                        {
                            Id = 4,
                            BadgeAchievementId = 104,
                            BadgeName = "Tide Badge",
                            CooldownHours = 12,
                            Description = "Marina believes language is best shared over a meal. Prove to her you can navigate any kitchen or restaurant conversation.",
                            GymOrder = 4,
                            Name = "Marina",
                            PassRatePercent = 80,
                            QuestionCount = 15,
                            RequiredCefrLevel = 1,
                            RequiredMemoryState = "Review",
                            Theme = 3,
                            Title = "Guardian of Food",
                            VocabThreshold = 20,
                            XpReward = 300,
                            XpThreshold = 1500
                        },
                        new
                        {
                            Id = 5,
                            BadgeAchievementId = 105,
                            BadgeName = "Spark Badge",
                            CooldownHours = 12,
                            Description = "Volt moves at the speed of electricity. Only the digitally fluent can keep up with his rapid-fire tech vocabulary.",
                            GymOrder = 5,
                            Name = "Volt",
                            PassRatePercent = 80,
                            QuestionCount = 15,
                            RequiredCefrLevel = 2,
                            RequiredMemoryState = "Learning",
                            Theme = 4,
                            Title = "Guardian of Technology",
                            VocabThreshold = 25,
                            XpReward = 400,
                            XpThreshold = 2500
                        },
                        new
                        {
                            Id = 6,
                            BadgeAchievementId = 106,
                            BadgeName = "Wing Badge",
                            CooldownHours = 12,
                            Description = "Aero has circled the globe many times over. She tests your ability to navigate the world — literally and linguistically.",
                            GymOrder = 6,
                            Name = "Aero",
                            PassRatePercent = 80,
                            QuestionCount = 15,
                            RequiredCefrLevel = 2,
                            RequiredMemoryState = "Review",
                            Theme = 5,
                            Title = "Guardian of Travel",
                            VocabThreshold = 25,
                            XpReward = 500,
                            XpThreshold = 3500
                        },
                        new
                        {
                            Id = 7,
                            BadgeAchievementId = 107,
                            BadgeName = "Glow Badge",
                            CooldownHours = 12,
                            Description = "Lumi radiates calm and wisdom. She demands precision — the language of health leaves no room for misunderstanding.",
                            GymOrder = 7,
                            Name = "Lumi",
                            PassRatePercent = 80,
                            QuestionCount = 15,
                            RequiredCefrLevel = 2,
                            RequiredMemoryState = "Review",
                            Theme = 6,
                            Title = "Guardian of Health",
                            VocabThreshold = 30,
                            XpReward = 600,
                            XpThreshold = 5000
                        },
                        new
                        {
                            Id = 8,
                            BadgeAchievementId = 108,
                            BadgeName = "Iron Badge",
                            CooldownHours = 12,
                            Description = "Brawl is the ultimate test of endurance. This battle will push your B2 vocabulary to the limit — no shortcuts allowed.",
                            GymOrder = 8,
                            Name = "Brawl",
                            PassRatePercent = 80,
                            QuestionCount = 15,
                            RequiredCefrLevel = 3,
                            RequiredMemoryState = "Learning",
                            Theme = 7,
                            Title = "Guardian of Sports",
                            VocabThreshold = 30,
                            XpReward = 800,
                            XpThreshold = 7000
                        });
                });

            modelBuilder.Entity("WordSoul.Domain.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("WordSoul.Domain.Entities.LearningSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BuffDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuffIcon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuffName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BuffPetId")
                        .HasColumnType("int");

                    b.Property<double?>("CatchRate")
                        .HasColumnType("float");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<double>("PetCatchBonus")
                        .HasColumnType("float");

                    b.Property<bool>("PetHintShield")
                        .HasColumnType("bit");

                    b.Property<int?>("PetId")
                        .HasColumnType("int");

                    b.Property<bool>("PetReducePenalty")
                        .HasColumnType("bit");

                    b.Property<double>("PetXpMultiplier")
                        .HasColumnType("float");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("VocabularySetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.HasIndex("UserId");

                    b.HasIndex("VocabularySetId");

                    b.ToTable("LearningSessions");
                });

            modelBuilder.Entity("WordSoul.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("WordSoul.Domain.Entities.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BaseFormId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("NextEvolutionId")
                        .HasColumnType("int");

                    b.Property<int?>("Order")
                        .HasColumnType("int");

                    b.Property<int>("Rarity")
                        .HasColumnType("int");

                    b.Property<int?>("RequiredLevel")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("WordSoul.Domain.Entities.SessionVocabulary", b =>
                {
                    b.Property<int>("LearningSessionId")
                        .HasColumnType("int");

                    b.Property<int>("VocabularyId")
                        .HasColumnType("int");

                    b.Property<int>("CurrentLevel")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSrsEvaluated")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("LearningSessionId", "VocabularyId");

                    b.HasIndex("VocabularyId");

                    b.ToTable("SessionVocabularies");
                });

            modelBuilder.Entity("WordSoul.Domain.Entities.SetRewardPet", b =>
                {
                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.Property<int>("VocabularySetId")
                        .HasColumnType("int");

                    b.Property<double>("DropRate")
                        .HasColumnType("float");

                    b.HasKey("PetId", "VocabularySetId");

                    b.HasIndex("VocabularySetId");

                    b.ToTable("SetRewardPets");
                });

            modelBuilder.Entity("WordSoul.Domain.Entities.SetVocabulary", b =>
                {
                    b.Property<int>("VocabularySetId")
                        .HasColumnType("int");

                    b.Property<int>("VocabularyId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("VocabularySetId", "VocabularyId");

                    b.HasIndex("Order");

                    b.HasIndex("VocabularyId");

                    b.HasIndex("VocabularySetId");

                    b.ToTable("SetVocabularies");
                });

            modelBuilder.Entity("WordSoul.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AP")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("HintBalance")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("XP")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WordSoul.Domain.Entities.UserAchievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AchievementId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ClaimedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsClaimed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("ProgressValue")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AchievementId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAchievements");
                });

            modelBuilder.Entity("WordSoul.Domain.Entities.UserDailyQuest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DailyQuestId")
                        .HasColumnType("int");

                    b.Property<bool>("IsClaimed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("Progress")
                        .HasColumnType("int");

                    b.Property<DateTime>("QuestDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DailyQuestId");

                    b.HasIndex("UserId", "DailyQuestId", "QuestDate")
                        .IsUnique();

                    b.ToTable("UserDailyQuests");
                });

            modelBuilder.Entity("WordSoul.Domain.Entities.UserGymProgress", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("GymLeaderId")
                        .HasColumnType("int");

                    b.Property<int>("BestScore")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DefeatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastAttemptAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TotalAttempts")
                        .HasColumnType("int");

                    b.HasKey("UserId", "GymLeaderId");

                    b.HasIndex("GymLeaderId");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("UserGymProgresses");
                });

            modelBuilder.Entity("WordSoul.Domain.Entities.UserItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId");

                    b.ToTable("UserItems");
                });

            modelBuilder.Entity("WordSoul.Domain.Entities.UserOwnedPet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AcquiredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.HasIndex("UserId");

                    b.ToTable("UserOwnedPets");
                });

            modelBuilder.Entity("WordSoul.Domain.Entities.UserVocabularyProgress", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VocabularyId")
                        .HasColumnType("int");

                    b.Property<int>("CorrectAttempt")
                        .HasColumnType("int");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("int");

                    b.Property<double>("EasinessFactor")
                        .HasColumnType("float");

                    b.Property<DateTime?>("FirstLearnedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Interval")
                        .HasColumnType("int");

                    b.Property<int>("LastGrade")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("MasteredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MemoryState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NextReviewTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Repetition")
                        .HasColumnType("int");

                    b.Property<decimal>("RetentionScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("TotalAttempt")
                        .HasColumnType("int");

                    b.Property<int>("WrongCount")
                        .HasColumnType("int");

                    b.HasKey("UserId", "VocabularyId");

                    b.HasIndex("VocabularyId");

                    b.ToTable("UserVocabularyProgresses");
                });

            modelBuilder.Entity("WordSoul.Domain.Entities.UserVocabularySet", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VocabularySetId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("TotalCompletedSession")
                        .HasColumnType("int");

                    b.HasKey("UserId", "VocabularySetId");

                    b.HasIndex("VocabularySetId");

                    b.ToTable("UserVocabularySets");
                });

            modelBuilder.Entity("WordSoul.Domain.Entities.Vocabulary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CEFRLevel")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExampleSentence")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Meaning")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PartOfSpeech")
                        .HasColumnType("int");

                    b.Property<string>("Pronunciation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PronunciationUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Word")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Word");

                    b.HasIndex("PartOfSpeech", "CEFRLevel");

                    b.ToTable("Vocabularies");
                });

            modelBuilder.Entity("WordSoul.Domain.Entities.VocabularyReviewHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("EaseFactorAfter")
                        .HasColumnType("float");

                    b.Property<double>("EaseFactorBefore")
                        .HasColumnType("float");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<int>("HintCount")
                        .HasColumnType("int");

                    b.Property<int>("IntervalAfter")
                        .HasColumnType("int");

                    b.Property<int>("IntervalBefore")
                        .HasColumnType("int");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("NextReviewAfter")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NextReviewBefore")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ResponseTimeSeconds")
                        .HasColumnType("float");

                    b.Property<DateTime>("ReviewTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VocabularyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VocabularyId");

                    b.ToTable("VocabularyReviewHistories");
                });

            modelBuilder.Entity("WordSoul.Domain.Entities.VocabularySet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("DifficultyLevel")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<int>("Theme")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("IsPublic");

                    b.HasIndex("Title");

                    b.HasIndex("Theme", "DifficultyLevel", "CreatedAt");

                    b.ToTable("VocabularySets");
                });

            modelBuilder.Entity("WordSoul.Domain.Entities.Achievement", b =>
                {
                    b.HasOne("WordSoul.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("WordSoul.Domain.Entities.ActivityLog", b =>
                {
                    b.HasOne("WordSoul.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WordSoul.Domain.Entities.AnswerRecord", b =>
                {
                    b.HasOne("WordSoul.Domain.Entities.LearningSession", "LearningSession")
                        .WithMany("AnswerRecords")
                        .HasForeignKey("LearningSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WordSoul.Domain.Entities.Vocabulary", "Vocabulary")
                        .WithMany("AnswerRecords")
                        .HasForeignKey("VocabularyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningSession");

                    b.Navigation("Vocabulary");
                });

            modelBuilder.Entity("WordSoul.Domain.Entities.BattleAnswer", b =>
                {
                    b.HasOne("WordSoul.Domain.Entities.BattleSession", "BattleSession")
                        .WithMany("Answers")
                        .HasForeignKey("BattleSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WordSoul.Domain.Entities.Vocabulary", "Vocabulary")
                        .WithMany()
                        .HasForeignKey("VocabularyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BattleSession");

                    b.Navigation("Vocabulary");
                });

            modelBuilder.Entity("WordSoul.Domain.Entities.BattleSession", b =>
                {
                    b.HasOne("WordSoul.Domain.Entities.User", "ChallengerUser")
                        .WithMany()
                        .HasForeignKey("ChallengerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WordSoul.Domain.Entities.GymLeader", "GymLeader")
                        .WithMany("BattleSessions")
                        .HasForeignKey("GymLeaderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WordSoul.Domain.Entities.User", "OpponentUser")
                        .WithMany()
                        .HasForeignKey("OpponentUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ChallengerUser");

                    b.Navigation("GymLeader");

                    b.Navigation("OpponentUser");
                });

            modelBuilder.Entity("WordSoul.Domain.Entities.GymLeader", b =>
                {
                    b.HasOne("WordSoul.Domain.Entities.Achievement", "BadgeAchievement")
                        .WithMany()
                        .HasForeignKey("BadgeAchievementId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BadgeAchievement");
                });

            modelBuilder.Entity("WordSoul.Domain.Entities.LearningSession", b =>
                {
                    b.HasOne("WordSoul.Domain.Entities.Pet", "Pet")
                        .WithMany()
                        .HasForeignKey("PetId");

                    b.HasOne("WordSoul.Domain.Entities.User", "User")
                        .WithMany("LearningSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WordSoul.Domain.Entities.VocabularySet", "VocabularySet")
                        .WithMany("LearningSessions")
                        .HasForeignKey("VocabularySetId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Pet");

                    b.Navigation("User");

                    b.Navigation("VocabularySet");
                });

            modelBuilder.Entity("WordSoul.Domain.Entities.Notification", b =>
                {
                    b.HasOne("WordSoul.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("WordSoul.Domain.Entities.SessionVocabulary", b =>
                {
                    b.HasOne("WordSoul.Domain.Entities.LearningSession", "LearningSession")
                        .WithMany("SessionVocabularies")
                        .HasForeignKey("LearningSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WordSoul.Domain.Entities.Vocabulary", "Vocabulary")
                        .WithMany("SessionVocabularies")
                        .HasForeignKey("VocabularyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LearningSession");

                    b.Navigation("Vocabulary");
                });

            modelBuilder.Entity("WordSoul.Domain.Entities.SetRewardPet", b =>
                {
                    b.HasOne("WordSoul.Domain.Entities.Pet", "Pet")
                        .WithMany("SetRewardPets")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WordSoul.Domain.Entities.VocabularySet", "VocabularySet")
                        .WithMany("SetRewardPets")
                        .HasForeignKey("VocabularySetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("VocabularySet");
                });

            modelBuilder.Entity("WordSoul.Domain.Entities.SetVocabulary", b =>
                {
                    b.HasOne("WordSoul.Domain.Entities.Vocabulary", "Vocabulary")
                        .WithMany("SetVocabularies")
                        .HasForeignKey("VocabularyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WordSoul.Domain.Entities.VocabularySet", "VocabularySet")
                        .WithMany("SetVocabularies")
                        .HasForeignKey("VocabularySetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vocabulary");

                    b.Navigation("VocabularySet");
                });

            modelBuilder.Entity("WordSoul.Domain.Entities.UserAchievement", b =>
                {
                    b.HasOne("WordSoul.Domain.Entities.Achievement", "Achievement")
                        .WithMany("UserAchievements")
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WordSoul.Domain.Entities.User", "User")
                        .WithMany("UserAchievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WordSoul.Domain.Entities.UserDailyQuest", b =>
                {
                    b.HasOne("WordSoul.Domain.Entities.DailyQuest", "DailyQuest")
                        .WithMany()
                        .HasForeignKey("DailyQuestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WordSoul.Domain.Entities.User", "User")
                        .WithMany("UserDailyQuests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyQuest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WordSoul.Domain.Entities.UserGymProgress", b =>
                {
                    b.HasOne("WordSoul.Domain.Entities.GymLeader", "GymLeader")
                        .WithMany("UserGymProgresses")
                        .HasForeignKey("GymLeaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WordSoul.Domain.Entities.User", "User")
                        .WithMany("UserGymProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GymLeader");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WordSoul.Domain.Entities.UserItem", b =>
                {
                    b.HasOne("WordSoul.Domain.Entities.Item", "Item")
                        .WithMany("UserItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WordSoul.Domain.Entities.User", "User")
                        .WithMany("UserItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WordSoul.Domain.Entities.UserOwnedPet", b =>
                {
                    b.HasOne("WordSoul.Domain.Entities.Pet", "Pet")
                        .WithMany("UserOwnedPets")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WordSoul.Domain.Entities.User", "User")
                        .WithMany("UserOwnedPets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WordSoul.Domain.Entities.UserVocabularyProgress", b =>
                {
                    b.HasOne("WordSoul.Domain.Entities.User", "User")
                        .WithMany("UserVocabularyProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WordSoul.Domain.Entities.Vocabulary", "Vocabulary")
                        .WithMany("UserVocabularyProgresses")
                        .HasForeignKey("VocabularyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Vocabulary");
                });

            modelBuilder.Entity("WordSoul.Domain.Entities.UserVocabularySet", b =>
                {
                    b.HasOne("WordSoul.Domain.Entities.User", "User")
                        .WithMany("UserVocabularySets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WordSoul.Domain.Entities.VocabularySet", "VocabularySet")
                        .WithMany("UserVocabularySets")
                        .HasForeignKey("VocabularySetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("VocabularySet");
                });

            modelBuilder.Entity("WordSoul.Domain.Entities.VocabularyReviewHistory", b =>
                {
                    b.HasOne("WordSoul.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WordSoul.Domain.Entities.Vocabulary", "Vocabulary")
                        .WithMany()
                        .HasForeignKey("VocabularyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Vocabulary");
                });

            modelBuilder.Entity("WordSoul.Domain.Entities.VocabularySet", b =>
                {
                    b.HasOne("WordSoul.Domain.Entities.User", "CreatedBy")
                        .WithMany("CreatedVocabularySets")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("WordSoul.Domain.Entities.Achievement", b =>
                {
                    b.Navigation("UserAchievements");
                });

            modelBuilder.Entity("WordSoul.Domain.Entities.BattleSession", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("WordSoul.Domain.Entities.GymLeader", b =>
                {
                    b.Navigation("BattleSessions");

                    b.Navigation("UserGymProgresses");
                });

            modelBuilder.Entity("WordSoul.Domain.Entities.Item", b =>
                {
                    b.Navigation("UserItems");
                });

            modelBuilder.Entity("WordSoul.Domain.Entities.LearningSession", b =>
                {
                    b.Navigation("AnswerRecords");

                    b.Navigation("SessionVocabularies");
                });

            modelBuilder.Entity("WordSoul.Domain.Entities.Pet", b =>
                {
                    b.Navigation("SetRewardPets");

                    b.Navigation("UserOwnedPets");
                });

            modelBuilder.Entity("WordSoul.Domain.Entities.User", b =>
                {
                    b.Navigation("CreatedVocabularySets");

                    b.Navigation("LearningSessions");

                    b.Navigation("Notifications");

                    b.Navigation("UserAchievements");

                    b.Navigation("UserDailyQuests");

                    b.Navigation("UserGymProgresses");

                    b.Navigation("UserItems");

                    b.Navigation("UserOwnedPets");

                    b.Navigation("UserVocabularyProgresses");

                    b.Navigation("UserVocabularySets");
                });

            modelBuilder.Entity("WordSoul.Domain.Entities.Vocabulary", b =>
                {
                    b.Navigation("AnswerRecords");

                    b.Navigation("SessionVocabularies");

                    b.Navigation("SetVocabularies");

                    b.Navigation("UserVocabularyProgresses");
                });

            modelBuilder.Entity("WordSoul.Domain.Entities.VocabularySet", b =>
                {
                    b.Navigation("LearningSessions");

                    b.Navigation("SetRewardPets");

                    b.Navigation("SetVocabularies");

                    b.Navigation("UserVocabularySets");
                });
#pragma warning restore 612, 618
        }
    }
}
