-- ============================================================
-- WordSoul - Pokemon Gen 1 Seed Data (151 Pokemon)
-- Generated: 2026-03-04 19:32:28
-- Images: pokemondb.net Black/White animated sprites
--
-- HOW TO USE:
--   1. Mở SSMS → Connect Azure SQL
--   2. File → Open → chọn file này
--   3. Đổi [your_database_name] thành tên DB thật
--   4. Execute (F5)
-- ============================================================

USE [your_database_name]; -- ⚠ THAY TÊN DB THẬT
GO

SET IDENTITY_INSERT [Pets] ON;

BEGIN TRANSACTION;
BEGIN TRY

    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (1,N'Bulbasaur',N'A strange seed was planted on its back at birth.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/bulbasaur.gif',1,4,1,NULL,2,16,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (2,N'Ivysaur',N'The bulb on its back grows by drawing energy from sunlight.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/ivysaur.gif',1,4,2,1,3,32,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (3,N'Venusaur',N'Its plant blooms when it absorbs solar energy, filling the air with a soothing scent.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/venusaur.gif',3,4,3,1,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (4,N'Charmander',N'The flame on its tail indicates its life force. If healthy its tail burns intensely.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/charmander.gif',1,1,4,NULL,5,16,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (5,N'Charmeleon',N'When it swings its burning tail intensely the air around it gets very hot.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/charmeleon.gif',1,1,5,4,6,36,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (6,N'Charizard',N'It spits fire hot enough to melt boulders and causes forest fires unintentionally.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/charizard.gif',3,1,6,4,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (7,N'Squirtle',N'When it retracts its long neck into its shell it squirts water with great force.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/squirtle.gif',1,2,7,NULL,8,16,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (8,N'Wartortle',N'Its fur-covered tail symbolizes longevity. It is a popular symbol of good health.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/wartortle.gif',1,2,8,7,9,36,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (9,N'Blastoise',N'It crushes its foes with powerful jets of water from the cannons on its back.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/blastoise.gif',3,2,9,7,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (10,N'Caterpie',N'Its short feet are tipped with suction pads that enable it to tirelessly climb slopes.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/caterpie.gif',0,11,10,NULL,11,7,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (11,N'Metapod',N'Inside its tough shell it quietly endures hardship as it prepares to evolve.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/metapod.gif',0,11,11,10,12,10,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (12,N'Butterfree',N'It collects honey daily. It can even gather pollen faster than a bee.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/butterfree.gif',2,11,12,10,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (13,N'Weedle',N'Often found in forests, it has a sharp, venomous stinger on its head.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/weedle.gif',0,11,13,NULL,14,7,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (14,N'Kakuna',N'Almost incapable of moving, this Pokemon can only harden its shell to protect itself.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/kakuna.gif',0,11,14,13,15,10,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (15,N'Beedrill',N'It has three poison stingers on its forelegs and tail. It targets the eyes first.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/beedrill.gif',2,11,15,13,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (16,N'Pidgey',N'A common sight in forests and cities. It hides in tall grass and rarely fights back.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/pidgey.gif',0,9,16,NULL,17,18,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (17,N'Pidgeotto',N'This Pokemon flies at Mach 2 speed, seeking prey and using its talons to grab them.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/pidgeotto.gif',0,9,17,16,18,36,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (18,N'Pidgeot',N'When it flies at high speed, the beautiful iridescence of its wings mesmerizes foes.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/pidgeot.gif',2,9,18,16,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (19,N'Rattata',N'Will chew on anything with its fangs. If you see one, many more live in the area.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/rattata.gif',0,0,19,NULL,20,20,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (20,N'Raticate',N'Its whiskers are extremely sensitive to air currents — it can tell what''s around it.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/raticate.gif',0,0,20,19,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (21,N'Spearow',N'Inept at flying high. However it can fly around very fast to protect its territory.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/spearow.gif',0,9,21,NULL,22,20,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (22,N'Fearow',N'With its huge and magnificent wings it can keep aloft without resting for a day.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/fearow.gif',0,9,22,21,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (23,N'Ekans',N'Moves silently and stealthily. Eats the eggs of birds such as Spearow whole.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/ekans.gif',0,7,23,NULL,24,22,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (24,N'Arbok',N'It is rumored that the ferocious warning pattern on its belly differs in six regions.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/arbok.gif',0,7,24,23,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (25,N'Pikachu',N'When several of these Pokemon gather, their electricity can build and cause lightning storms.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/pikachu.gif',2,3,25,NULL,26,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (26,N'Raichu',N'Its tail serves as a ground to protect itself from its own high-voltage zaps.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/raichu.gif',2,3,26,25,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (27,N'Sandshrew',N'Burrows deep underground in arid desert areas. Surfaces only to hunt for food.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/sandshrew.gif',0,8,27,NULL,28,22,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (28,N'Sandslash',N'Curls up into a spiny ball when threatened. Its sharp claws are used to dig burrows.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/sandslash.gif',0,8,28,27,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (29,N'Nidoran F',N'Although small its venomous barbs render it dangerous. The female has smaller horns.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/nidoran-f.gif',0,7,29,NULL,30,16,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (30,N'Nidorina',N'The female raises its rough hide when angry. It uses its small horns to battle.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/nidorina.gif',0,7,30,29,31,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (31,N'Nidoqueen',N'Its body is encased in rock-hard scales. The hard scales provide strong protection.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/nidoqueen.gif',1,7,31,29,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (32,N'Nidoran M',N'Stiffens its ears to sense danger. The larger its horns the more powerful its venom.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/nidoran-m.gif',0,7,32,NULL,33,16,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (33,N'Nidorino',N'An aggressive Pokemon that is quick to attack. The horn can inject devastating venom.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/nidorino.gif',0,7,33,32,34,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (34,N'Nidoking',N'It uses its powerful tail in battle to topple telephone poles and trees with ease.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/nidoking.gif',1,7,34,32,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (35,N'Clefairy',N'Widely believed to have come from outer space. They gather on moonlit nights.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/clefairy.gif',1,0,35,NULL,36,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (36,N'Clefable',N'A timid fairy Pokemon that is rarely seen. It will run and hide the moment it senses people.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/clefable.gif',1,0,36,35,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (37,N'Vulpix',N'At birth it has just one tail. The tail splits from its tip as it grows older.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/vulpix.gif',1,1,37,NULL,38,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (38,N'Ninetales',N'Very smart and very vengeful. Grabbing one of its tails could result in a 1000-year curse.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/ninetales.gif',2,1,38,37,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (39,N'Jigglypuff',N'When its huge eyes light up it sings a mysteriously soothing melody that lulls enemies to sleep.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/jigglypuff.gif',1,0,39,NULL,40,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (40,N'Wigglytuff',N'The body is soft and rubbery. When angered it will suck in air and inflate itself to an enormous size.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/wigglytuff.gif',1,0,40,39,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (41,N'Zubat',N'Forms colonies in perpetually dark places. Uses ultrasonic waves to identify and approach targets.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/zubat.gif',0,7,41,NULL,42,22,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (42,N'Golbat',N'Once it bites its victim it will not stop draining energy from the victim even if it gets too heavy to fly.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/golbat.gif',0,7,42,41,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (43,N'Oddish',N'During the day it keeps its face buried in the ground. At night it roams about and scatters its seeds.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/oddish.gif',1,4,43,NULL,44,21,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (44,N'Gloom',N'The petals are said to bring about feelings of happiness when smelled. Its pistil oozes a sticky nectar.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/gloom.gif',1,4,44,43,45,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (45,N'Vileplume',N'It has the world''s largest petals. They are stored with toxic pollen which it scatters on approach.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/vileplume.gif',2,4,45,43,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (46,N'Paras',N'Burrows to suck tree roots. Mushrooms named tochukaso grow on its back and absorb the host.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/paras.gif',0,11,46,NULL,47,24,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (47,N'Parasect',N'A host-parasite pair where the parasite controls the host. Spores spread from its mushroom on its back.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/parasect.gif',0,11,47,46,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (48,N'Venonat',N'Lives in the shadows of tall trees where it eats insects. It is attracted by light.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/venonat.gif',0,11,48,NULL,49,31,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (49,N'Venomoth',N'The dust-like scales covering its wings are color coded to identify the types of poison it has.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/venomoth.gif',0,11,49,48,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (50,N'Diglett',N'A Pokemon that lives underground. It burrows through the ground at a shallow depth.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/diglett.gif',0,8,50,NULL,51,26,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (51,N'Dugtrio',N'A team of Diglett triplets. It triggers huge earthquakes by burrowing 60 miles underground.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/dugtrio.gif',0,8,51,50,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (52,N'Meowth',N'Extremely greedy it sees shiny things and instantly swipes them. It hides its collection.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/meowth.gif',0,0,52,NULL,53,28,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (53,N'Persian',N'Although its fur has many admirers it is tough to raise as a pet due to its fickle meanness.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/persian.gif',0,0,53,52,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (54,N'Psyduck',N'While lulling its enemies with its vacant look it makes them sustain damage by blasting them with psychic waves.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/psyduck.gif',1,2,54,NULL,55,33,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (55,N'Golduck',N'Often seen swimming elegantly by lakesides. It is often mistaken for the Japanese Kappa.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/golduck.gif',1,2,55,54,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (56,N'Mankey',N'Extremely quick to anger. It takes only a slight provocation to send it into a frenzy.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/mankey.gif',0,6,56,NULL,57,28,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (57,N'Primeape',N'Always furious and rampaging it may snap a neck or two while trembling with rage.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/primeape.gif',0,6,57,56,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (58,N'Growlithe',N'Very protective of its territory. It will bark and bite to keep intruders away.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/growlithe.gif',1,1,58,NULL,59,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (59,N'Arcanine',N'A Pokemon that has long been admired for its beauty. It runs agilely as if on wings.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/arcanine.gif',2,1,59,58,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (60,N'Poliwag',N'Its newly grown legs prevent it from running. It appears to prefer swimming over everything.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/poliwag.gif',0,2,60,NULL,61,25,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (61,N'Poliwhirl',N'Capable of living in or out of water. When out of water it sweats to keep its body slimy.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/poliwhirl.gif',0,2,61,60,62,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (62,N'Poliwrath',N'An adept swimmer at both the front crawl and breaststroke. Easily overtakes Olympic swimmers.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/poliwrath.gif',2,2,62,60,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (63,N'Abra',N'Using its ability to read minds it will identify impending danger and teleport to safety.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/abra.gif',1,10,63,NULL,64,16,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (64,N'Kadabra',N'It emits special alpha waves from its body that induce headaches just by being close by.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/kadabra.gif',1,10,64,63,65,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (65,N'Alakazam',N'Its brain can outperform a supercomputer. Its IQ is said to be around 5000.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/alakazam.gif',2,10,65,63,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (66,N'Machop',N'Loves to build its muscles. It trains by lifting boulders in gravelly mountain ranges.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/machop.gif',1,6,66,NULL,67,28,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (67,N'Machoke',N'Its muscular body is so powerful it must wear a power-save belt to regulate its power.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/machoke.gif',1,6,67,66,68,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (68,N'Machamp',N'It quickly swings its four arms to rock its opponents with a flurry of punches and chops.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/machamp.gif',3,6,68,66,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (69,N'Bellsprout',N'A carnivorous Pokemon that traps and absorbs insects. Its thin body can whip rapidly.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/bellsprout.gif',1,4,69,NULL,70,21,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (70,N'Weepinbell',N'It looks like a plant but it is able to move around. It catches bugs by surprising them.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/weepinbell.gif',1,4,70,69,71,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (71,N'Victreebel',N'Said to live in huge colonies deep in jungles where it swallows anything that approaches.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/victreebel.gif',2,4,71,69,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (72,N'Tentacool',N'Drifts in shallow seas. Absorbs sunlight to convert it into beam energy.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/tentacool.gif',0,2,72,NULL,73,30,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (73,N'Tentacruel',N'The tentacles can paralyze prey with venom. It has ninety-six and can shoot venom from all of them.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/tentacruel.gif',0,2,73,72,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (74,N'Geodude',N'Found in fields and mountains. Mistaking them for boulders people often step on them.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/geodude.gif',0,12,74,NULL,75,25,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (75,N'Graveler',N'Rolls down slopes to move. It rolls over any obstacle without slowing or changing course.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/graveler.gif',0,12,75,74,76,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (76,N'Golem',N'Its boulder-like body is extremely hard. It sheds its skin once a year.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/golem.gif',2,12,76,74,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (77,N'Ponyta',N'Its legs grow strong while it runs around. It runs in fields and mountains from morning to night.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/ponyta.gif',1,1,77,NULL,78,40,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (78,N'Rapidash',N'Very competitive and loves to race. It will chase anything that moves fast in hopes of racing.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/rapidash.gif',2,1,78,77,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (79,N'Slowpoke',N'Incredibly slow and dopey. It takes 5 seconds to feel pain when under attack.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/slowpoke.gif',1,2,79,NULL,80,37,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (80,N'Slowbro',N'The Shellder that is latched onto its tail is said to feed on Slowbro''s left-over scraps.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/slowbro.gif',2,2,80,79,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (81,N'Magnemite',N'Uses anti-gravity to stay suspended. Electro waves from thunderheads trigger it to swarm.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/magnemite.gif',1,3,81,NULL,82,30,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (82,N'Magneton',N'Formed by three Magnemite linked together. Nearby electronics are affected by its magnetism.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/magneton.gif',1,3,82,81,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (83,N'Farfetchd',N'The stalk it holds is made from a plant grown specially in most places. Always will be holding it.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/farfetchd.gif',2,0,83,NULL,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (84,N'Doduo',N'A bird that makes up for its poor flying with its fast foot speed. Leaves giant footprints.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/doduo.gif',0,9,84,NULL,85,31,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (85,N'Dodrio',N'Uses its three brains to execute complex plans. With three heads it can think three times as fast.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/dodrio.gif',0,9,85,84,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (86,N'Seel',N'The protruding horn on its forehead is very hard. It is used for bashing through thick ice.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/seel.gif',0,2,86,NULL,87,34,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (87,N'Dewgong',N'Loves to play in cold waters. Stores thermal energy in its body. Becomes more active in cold weather.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/dewgong.gif',0,2,87,86,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (88,N'Grimer',N'Appears in filthy areas. Thrives by sucking up polluted sludge that is pumped out of factories.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/grimer.gif',0,7,88,NULL,89,38,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (89,N'Muk',N'Absorbing filth causes it to grow. They group together in dirty cities and sewage plants.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/muk.gif',0,7,89,88,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (90,N'Shellder',N'Its shell is harder than diamond. Inside is a pearl found nowhere else. Spits pearls at enemies.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/shellder.gif',0,2,90,NULL,91,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (91,N'Cloyster',N'Once it slams its shell shut it is impossible to open even with great force.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/cloyster.gif',2,2,91,90,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (92,N'Gastly',N'Almost invisible when underground it floats upward as night falls. It will curse anyone who touches it.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/gastly.gif',1,13,92,NULL,93,25,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (93,N'Haunter',N'Because of its ability to slip through block walls it is said to be from another dimension.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/haunter.gif',1,13,93,92,94,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (94,N'Gengar',N'To steal the warmth of a person it will enter the room of a healthy person and hang in the shadow.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/gengar.gif',3,13,94,92,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (95,N'Onix',N'As it grows the stone portions of its body harden to become similar to a diamond — but colored black.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/onix.gif',1,12,95,NULL,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (96,N'Drowzee',N'Puts enemies to sleep then eats their dreams. Occasionally gets sick from eating bad dreams.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/drowzee.gif',1,10,96,NULL,97,26,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (97,N'Hypno',N'When it locks eyes with an enemy it will use a mix of PSI moves such as Hypnosis and Confusion.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/hypno.gif',1,10,97,96,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (98,N'Krabby',N'Its pincers are not only powerful weapons they are used for balance when walking sideways.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/krabby.gif',0,2,98,NULL,99,28,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (99,N'Kingler',N'The larger pincer has 10000 HP of crushing power. However its huge claw makes it hard to aim.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/kingler.gif',0,2,99,98,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (100,N'Voltorb',N'Usually found in power plants. Explodes with little provocation. Considered a problem.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/voltorb.gif',0,3,100,NULL,101,30,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (101,N'Electrode',N'Explodes if bored. Stores electricity in its body and will become unstable and explode.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/electrode.gif',0,3,101,100,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (102,N'Exeggcute',N'Often mistaken for eggs. When disturbed they quickly gather and attack in swarms.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/exeggcute.gif',1,4,102,NULL,103,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (103,N'Exeggutor',N'Its three heads think independently. However they are friendly and never argue.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/exeggutor.gif',2,4,103,102,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (104,N'Cubone',N'Wears the skull of its deceased mother. Its cries echo inside the skull and come out as a sad melody.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/cubone.gif',1,8,104,NULL,105,28,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (105,N'Marowak',N'The bone it holds is its key weapon. It throws the bone skillfully like a boomerang.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/marowak.gif',1,8,105,104,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (106,N'Hitmonlee',N'When in a hurry its legs lengthen progressively. It can reach a fleeing foe in an instant.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/hitmonlee.gif',2,6,106,NULL,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (107,N'Hitmonchan',N'Said to possess the spirit of a boxer who had been working toward a world championship.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/hitmonchan.gif',2,6,107,NULL,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (108,N'Lickitung',N'Its tongue spans 6.5 feet and moves more freely than its forelegs. Its saliva melts anything organic.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/lickitung.gif',2,0,108,NULL,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (109,N'Koffing',N'Because it stores several kinds of toxic gases in its body it is prone to exploding without warning.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/koffing.gif',1,7,109,NULL,110,35,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (110,N'Weezing',N'Where two kinds of poison gases meet two Koffing can fuse over many years into one Pokemon.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/weezing.gif',1,7,110,109,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (111,N'Rhyhorn',N'Its massive bones are 1000 times harder than human bones. It can easily knock a trailer flying.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/rhyhorn.gif',0,8,111,NULL,112,42,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (112,N'Rhydon',N'Protected by an armor-like hide it is capable of living in molten lava of 3600 degrees.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/rhydon.gif',2,8,112,111,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (113,N'Chansey',N'A rare and kind-hearted Pokemon that shares its nutritious eggs generously.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/chansey.gif',2,0,113,NULL,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (114,N'Tangela',N'The whole body is wrapped in blue plant vines. The vines sway as it walks.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/tangela.gif',2,4,114,NULL,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (115,N'Kangaskhan',N'The young one in its pouch peers out to learn more about the world with its curious eyes.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/kangaskhan.gif',2,0,115,NULL,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (116,N'Horsea',N'Capable of swimming swiftly by cleverly flapping its fan-like tail fins.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/horsea.gif',0,2,116,NULL,117,32,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (117,N'Seadra',N'Capable of swimming backwards by rapidly flapping its wing-like pectoral fins and stout tail.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/seadra.gif',0,2,117,116,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (118,N'Goldeen',N'It is a well-known swimmer. Its large and elegant fins billow like expressive skirts.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/goldeen.gif',0,2,118,NULL,119,33,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (119,N'Seaking',N'In autumn its body becomes more fatty in preparing to propose to a mate. It takes on a redder color.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/seaking.gif',0,2,119,118,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (120,N'Staryu',N'Even though its body is separated it is fine. Examine the red core of its body — it flickers.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/staryu.gif',1,2,120,NULL,121,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (121,N'Starmie',N'Its central core glows with the seven colors of the rainbow. Some people call it the gem of the sea.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/starmie.gif',2,2,121,120,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (122,N'Mr Mime',N'If interrupted while miming it will slap around the offender with its broad hands.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/mr-mime.gif',2,10,122,NULL,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (123,N'Scyther',N'With ninja-like agility and speed it can create the illusion that there is more than one.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/scyther.gif',2,11,123,NULL,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (124,N'Jynx',N'It seductively wiggles its hips as it walks. It can cause people to dance in unison with it.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/jynx.gif',2,10,124,NULL,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (125,N'Electabuzz',N'Normally found near power plants it can wander into populated areas if there is a power outage.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/electabuzz.gif',2,3,125,NULL,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (126,N'Magmar',N'Its body always burns and floats in lava. It is known to cause forest fires unintentionally.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/magmar.gif',2,1,126,NULL,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (127,N'Pinsir',N'If it grips an enemy with its pincers it will not stop squeezing until the enemy is torn in half.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/pinsir.gif',2,11,127,NULL,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (128,N'Tauros',N'When whipping itself with its three tails it becomes agitated and will charge blindly.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/tauros.gif',2,0,128,NULL,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (129,N'Magikarp',N'A pathetic excuse for a Pokemon that is only capable of flopping and splashing.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/magikarp.gif',0,2,129,NULL,130,20,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (130,N'Gyarados',N'Once it begins to rampage it will not stop until everything is obliterated. It can devastate cities.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/gyarados.gif',3,2,130,129,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (131,N'Lapras',N'A Pokemon that has been overhunted almost to extinction. It is gentle and transports people on its back.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/lapras.gif',3,2,131,NULL,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (132,N'Ditto',N'Capable of copying an enemy''s genetic code to instantly transform itself into a duplicate.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/ditto.gif',1,0,132,NULL,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (133,N'Eevee',N'An evolutionary process began from irregular mutations. It has the potential to evolve into many forms.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/eevee.gif',2,0,133,NULL,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (134,N'Vaporeon',N'Somewhat rare in the wild. Vaporeon evolved close to water. Its cell composition is similar to water molecules.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/vaporeon.gif',3,2,134,133,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (135,N'Jolteon',N'It accumulates negative ions in the atmosphere to blast out 10000-volt lightning bolts.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/jolteon.gif',3,3,135,133,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (136,N'Flareon',N'When storing thermal energy in its body its temperature could soar to over 1600 degrees.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/flareon.gif',3,1,136,133,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (137,N'Porygon',N'A Pokemon that consists entirely of programming code. It is capable of moving freely in cyberspace.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/porygon.gif',2,0,137,NULL,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (138,N'Omanyte',N'An ancient and long-since-extinct Pokemon that has been regenerated from a fossil.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/omanyte.gif',0,12,138,NULL,139,40,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (139,N'Omastar',N'A prehistoric and extinct Pokemon which used its tentacles to capture prey.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/omastar.gif',2,12,139,138,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (140,N'Kabuto',N'A prehistoric Pokemon that lived in ancient seas 300 million years ago.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/kabuto.gif',0,12,140,NULL,141,40,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (141,N'Kabutops',N'Its sleek shape is perfect for swimming. It slices prey with its sharp sickles and drinks the body fluids.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/kabutops.gif',2,12,141,140,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (142,N'Aerodactyl',N'A ferocious Pokemon from the age of dinosaurs. Though long extinct it was regenerated from old amber.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/aerodactyl.gif',2,12,142,NULL,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (143,N'Snorlax',N'Very lazy. Just eats and sleeps. As its rotund bulk builds it becomes steadily more slothful.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/snorlax.gif',3,0,143,NULL,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (144,N'Articuno',N'A legendary bird Pokemon that can control ice. The flapping of its wings chills the air.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/articuno.gif',4,5,144,NULL,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (145,N'Zapdos',N'A legendary bird Pokemon that has the ability to control electricity. It becomes energized by lightning strikes.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/zapdos.gif',4,3,145,NULL,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (146,N'Moltres',N'A legendary bird Pokemon that can control fire. When it flaps its wings it showers its feathers in flames.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/moltres.gif',4,1,146,NULL,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (147,N'Dratini',N'Long thought to be a myth. It inhabits the water and sheds its skin regularly.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/dratini.gif',1,14,147,NULL,148,30,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (148,N'Dragonair',N'A mystical Pokemon that exudes a gentle aura. Has the ability to change climate conditions.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/dragonair.gif',2,14,148,147,149,55,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (149,N'Dragonite',N'An extremely rare marine Pokemon. It is said to make its home somewhere in the sea.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/dragonite.gif',3,14,149,147,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (150,N'Mewtwo',N'A Pokemon created by recombining Mew''s genes. It is said to be the most powerful Pokemon ever.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/mewtwo.gif',4,10,150,NULL,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (151,N'Mew',N'So rare it is still said to be a mirage. Many scientists wonder if it is really the ancestor of all Pokemon.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/mew.gif',4,10,151,NULL,NULL,NULL,GETUTCDATE(),1);

    COMMIT TRANSACTION;
    PRINT N'[OK] Seed thanh cong 151 Pokemon!';
END TRY
BEGIN CATCH
    ROLLBACK TRANSACTION;
    SET IDENTITY_INSERT [Pets] OFF;
    PRINT N'[ERR] Loi: ' + ERROR_MESSAGE();
END CATCH

SET IDENTITY_INSERT [Pets] OFF;
