-- ============================================================
-- WordSoul - Pokemon Gen 2 Seed Data (151 Pokemon)
-- Generated: 2026-03-26 17:42:05
-- Images: pokemondb.net Black/White animated sprites
--
-- HOW TO USE:
--   1. Mở SSMS → Connect Azure SQL
--   2. File → Open → chọn file này
--   3. Đổi [your_database_name] thành tên DB thật
--   4. Execute (F5)
-- ============================================================

USE [your_database_name]; -- ⚠ THAY TÊN DB THẬT
GO

SET IDENTITY_INSERT [Pets] ON;

BEGIN TRANSACTION;
BEGIN TRY

    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (152,N'Chikorita',N'A sweet aroma gently wafts from the leaf on its head.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/chikorita.gif',1,4,152,NULL,153,16,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (153,N'Bayleef',N'The scent of spices comes from around its neck.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/bayleef.gif',1,4,153,152,154,32,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (154,N'Meganium',N'The aroma from its petals contains a substance that calms aggressive feelings.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/meganium.gif',3,4,154,152,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (155,N'Cyndaquil',N'It usually stays hunched over. If it is angry, its back erupts with flames.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/cyndaquil.gif',1,1,155,NULL,156,14,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (156,N'Quilava',N'Before battle, it turns its back on the opponent to demonstrate how ferociously its fire blazes.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/quilava.gif',1,1,156,155,157,36,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (157,N'Typhlosion',N'It has a secret, devastating move. It rubs its blazing fur together to cause huge explosions.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/typhlosion.gif',3,1,157,155,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (158,N'Totodile',N'Its well-developed jaws are powerful and capable of crushing anything.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/totodile.gif',1,2,158,NULL,159,18,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (159,N'Croconaw',N'Once it bites something, it won''t let go until it loses its fangs.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/croconaw.gif',1,2,159,158,160,30,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (160,N'Feraligatr',N'When it bites with its massive and powerful jaws, it shakes its head and savagely tears its victim up.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/feraligatr.gif',3,2,160,158,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (161,N'Sentret',N'It stands on its tail so it can see a long way.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/sentret.gif',0,0,161,NULL,162,15,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (162,N'Furret',N'It lives in narrow burrows that fit its slim body.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/furret.gif',0,0,162,161,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (163,N'Hoothoot',N'It always stands on one foot.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/hoothoot.gif',0,9,163,NULL,164,20,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (164,N'Noctowl',N'Its eyes are specially adapted. They concentrate even faint light.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/noctowl.gif',1,9,164,163,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (165,N'Ledyba',N'It is timid and clusters together with others.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/ledyba.gif',0,11,165,NULL,166,18,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (166,N'Ledian',N'It uses starlight as energy.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/ledian.gif',1,11,166,165,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (167,N'Spinarak',N'It spins webs using fine threads.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/spinarak.gif',0,11,167,NULL,168,22,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (168,N'Ariados',N'It binds its prey with string-like silk.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/ariados.gif',1,11,168,167,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (169,N'Crobat',N'It flies silently through the night.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/crobat.gif',2,7,169,41,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (170,N'Chinchou',N'It uses positive and negative electricity.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/chinchou.gif',1,2,170,NULL,171,27,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (171,N'Lanturn',N'The light it emits is so bright.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/lanturn.gif',2,2,171,170,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (172,N'Pichu',N'It plays with electricity.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/pichu.gif',1,3,172,NULL,25,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (173,N'Cleffa',N'Because of its unusual star-like silhouette.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/cleffa.gif',1,0,173,NULL,35,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (174,N'Igglybuff',N'It has a very soft body.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/igglybuff.gif',1,0,174,NULL,39,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (175,N'Togepi',N'The shell seems to be filled with joy.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/togepi.gif',2,0,175,NULL,176,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (176,N'Togetic',N'They say that it will appear before kindhearted people.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/togetic.gif',2,0,176,175,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (177,N'Natu',N'It is extremely good at climbing trees.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/natu.gif',1,10,177,NULL,178,25,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (178,N'Xatu',N'It is said to stay still and watch the sun all day.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/xatu.gif',2,10,178,177,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (179,N'Mareep',N'Its wool rubs together and builds static electricity.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/mareep.gif',1,3,179,NULL,180,15,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (180,N'Flaaffy',N'Its fluffy wool stores electricity.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/flaaffy.gif',1,3,180,179,181,30,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (181,N'Ampharos',N'The tip of its tail shines brightly.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/ampharos.gif',3,3,181,179,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (182,N'Bellossom',N'Plentiful in the tropics.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/bellossom.gif',2,4,182,43,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (183,N'Marill',N'The tip of its tail is filled with oil.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/marill.gif',1,2,183,NULL,184,18,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (184,N'Azumarill',N'It lives in water almost all day.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/azumarill.gif',2,2,184,183,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (185,N'Sudowoodo',N'Although it always pretends to be a tree.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/sudowoodo.gif',1,12,185,NULL,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (186,N'Politoed',N'The curled hair on its head is proof.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/politoed.gif',2,2,186,60,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (187,N'Hoppip',N'It drifts on the wind.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/hoppip.gif',0,4,187,NULL,188,18,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (188,N'Skiploom',N'The bloom on top opens and closes.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/skiploom.gif',0,4,188,187,189,27,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (189,N'Jumpluff',N'Once it catches the wind.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/jumpluff.gif',1,4,189,187,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (190,N'Aipom',N'It lives atop tall trees.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/aipom.gif',1,0,190,NULL,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (191,N'Sunkern',N'It tries to move as little as possible.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/sunkern.gif',0,4,191,NULL,192,14,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (192,N'Sunflora',N'It converts sunlight into energy.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/sunflora.gif',1,4,192,191,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (193,N'Yanma',N'It can see 360 degrees.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/yanma.gif',1,11,193,NULL,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (194,N'Wooper',N'This carefree Pokémon has an easygoing nature.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/wooper.gif',0,2,194,NULL,195,20,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (195,N'Quagsire',N'It has a sluggish nature.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/quagsire.gif',1,2,195,194,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (196,N'Espeon',N'It uses the fine hair that covers its body.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/espeon.gif',3,10,196,133,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (197,N'Umbreon',N'When darkness falls, the rings begin to glow.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/umbreon.gif',3,15,197,133,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (198,N'Murkrow',N'Feared and loathed by many.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/murkrow.gif',1,15,198,NULL,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (199,N'Slowking',N'Every time it yawns, Shellder injects more poison.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/slowking.gif',3,2,199,79,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (200,N'Misdreavus',N'It loves to bite and yank people''s hair.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/misdreavus.gif',1,13,200,NULL,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (201,N'Unown',N'Their shapes look like hieroglyphs.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/unown.gif',1,10,201,NULL,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (202,N'Wobbuffet',N'It hates light and shock.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/wobbuffet.gif',2,10,202,360,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (203,N'Girafarig',N'Its tail has a small brain.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/girafarig.gif',1,0,203,NULL,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (204,N'Pineco',N'It hangs from a tree branch.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/pineco.gif',0,11,204,NULL,205,31,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (205,N'Forretress',N'Its entire body is shielded by a steel-hard shell.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/forretress.gif',2,11,205,204,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (206,N'Dunsparce',N'It hides deep inside caves.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/dunsparce.gif',1,0,206,NULL,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (207,N'Gligar',N'It glides without a sound.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/gligar.gif',1,8,207,NULL,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (208,N'Steelix',N'Its body has been compressed deep underground.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/steelix.gif',3,16,208,95,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (209,N'Snubbull',N'Although it looks frightening.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/snubbull.gif',1,0,209,NULL,210,23,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (210,N'Granbull',N'It is actually timid.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/granbull.gif',2,0,210,209,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (211,N'Qwilfish',N'To fire its poison spikes.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/qwilfish.gif',1,2,211,NULL,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (212,N'Scizor',N'It swings its eye-patterned pincers.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/scizor.gif',3,11,212,123,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (213,N'Shuckle',N'The berries it stores turn into juice.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/shuckle.gif',2,12,213,NULL,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (214,N'Heracross',N'With its Herculean powers.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/heracross.gif',2,6,214,NULL,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (215,N'Sneasel',N'It is extremely vicious.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/sneasel.gif',2,15,215,NULL,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (216,N'Teddiursa',N'It licks its paws.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/teddiursa.gif',1,0,216,NULL,217,30,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (217,N'Ursaring',N'It is said to be a good swimmer.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/ursaring.gif',2,0,217,216,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (218,N'Slugma',N'A common sight in volcanic areas.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/slugma.gif',0,1,218,NULL,219,38,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (219,N'Magcargo',N'Its shell is made of hardened magma.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/magcargo.gif',1,1,219,218,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (220,N'Swinub',N'It rubs its snout on the ground.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/swinub.gif',0,5,220,NULL,221,33,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (221,N'Piloswine',N'Because the long hair all over its body obscures its sight.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/piloswine.gif',1,5,221,220,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (222,N'Corsola',N'They live in warm southern seas.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/corsola.gif',1,2,222,NULL,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (223,N'Remoraid',N'It shoots water out of its mouth.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/remoraid.gif',0,2,223,NULL,224,25,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (224,N'Octillery',N'It traps enemies with its suction-cupped tentacles.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/octillery.gif',1,2,224,223,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (225,N'Delibird',N'It carries food all day long.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/delibird.gif',1,5,225,NULL,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (226,N'Mantine',N'As it majestically swims.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/mantine.gif',2,2,226,458,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (227,N'Skarmory',N'Its body is encased in a sturdy shell of steel.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/skarmory.gif',2,16,227,NULL,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (228,N'Houndour',N'It uses different kinds of cries.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/houndour.gif',1,15,228,NULL,229,24,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (229,N'Houndoom',N'If you are burned by the flames.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/houndoom.gif',2,15,229,228,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (230,N'Kingdra',N'It is said that it sleeps on the seafloor.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/kingdra.gif',3,2,230,117,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (231,N'Phanpy',N'It is strong despite its compact size.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/phanpy.gif',1,8,231,NULL,232,25,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (232,N'Donphan',N'It has sharp, hard tusks.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/donphan.gif',2,8,232,231,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (233,N'Porygon2',N'This upgraded version of Porygon.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/porygon2.gif',3,0,233,137,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (234,N'Stantler',N'Those who stare at its antlers.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/stantler.gif',1,0,234,NULL,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (235,N'Smeargle',N'It marks its territory using a fluid.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/smeargle.gif',2,0,235,NULL,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (236,N'Tyrogue',N'It is always bursting with energy.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/tyrogue.gif',1,6,236,NULL,NULL,20,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (237,N'Hitmontop',N'If you become enchanted by its smooth.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/hitmontop.gif',2,6,237,236,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (238,N'Smoochum',N'It always rocks its head slowly.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/smoochum.gif',1,10,238,NULL,124,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (239,N'Elekid',N'It generates electricity.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/elekid.gif',1,3,239,NULL,125,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (240,N'Magby',N'Each and every time it inhales.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/magby.gif',1,1,240,NULL,126,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (241,N'Miltank',N'Its milk is packed with nutrition.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/miltank.gif',2,0,241,NULL,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (242,N'Blissey',N'Anyone who takes even one bite.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/blissey.gif',3,0,242,113,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (243,N'Raikou',N'The rain clouds it carries.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/raikou.gif',4,3,243,NULL,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (244,N'Entei',N'A Pokemon that races across the land.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/entei.gif',4,1,244,NULL,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (245,N'Suicune',N'Said to be the embodiment of north winds.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/suicune.gif',4,2,245,NULL,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (246,N'Larvitar',N'It feeds on soil.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/larvitar.gif',1,12,246,NULL,247,30,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (247,N'Pupitar',N'Its shell is as hard as bedrock.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/pupitar.gif',2,12,247,246,248,55,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (248,N'Tyranitar',N'Its body can''t be harmed by any sort of attack.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/tyranitar.gif',3,12,248,246,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (249,N'Lugia',N'It sleeps in a deep-sea trench.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/lugia.gif',4,10,249,NULL,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (250,N'Ho-oh',N'Legends claim this Pokemon flies the world''s skies.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/ho-oh.gif',4,1,250,NULL,NULL,NULL,GETUTCDATE(),1);
    INSERT INTO [Pets] ([Id],[Name],[Description],[ImageUrl],[Rarity],[Type],[Order],[BaseFormId],[NextEvolutionId],[RequiredLevel],[CreatedAt],[IsActive]) VALUES (251,N'Celebi',N'It has the power to travel across time.',N'https://img.pokemondb.net/sprites/black-white/anim/normal/celebi.gif',4,10,251,NULL,NULL,NULL,GETUTCDATE(),1);

    COMMIT TRANSACTION;
    PRINT N'[OK] Seed thanh cong 100 Pokemon!';
END TRY
BEGIN CATCH
    ROLLBACK TRANSACTION;
    SET IDENTITY_INSERT [Pets] OFF;
    PRINT N'[ERR] Loi: ' + ERROR_MESSAGE();
END CATCH

SET IDENTITY_INSERT [Pets] OFF;
