name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'wordsoul-admin/**' # Chỉ chạy khi có thay đổi trong thư mục Admin
      - '.github/workflows/azure-static-web-apps-lively-mushroom-090b44800.yml'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths:
      - 'wordsoul-admin/**'
      - '.github/workflows/azure-static-web-apps-lively-mushroom-090b44800.yml'

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LIVELY_MUSHROOM_090B44800 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          ###### Cấu hình Repository/Build ######
          app_location: "/wordsoul-admin"   # Thư mục gốc của project Next.js
          api_location: ""                 # Để trống nếu không dùng Azure Functions
          output_location: ""              # BẮT BUỘC để trống ("") cho Next.js Hybrid apps
          ###### Kết thúc cấu hình ######
        env:
          NEXT_PUBLIC_API_URL: https://wordsoul-api-dev-hybybqh9dhhzhped.southeastasia-01.azurewebsites.net/api

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LIVELY_MUSHROOM_090B44800 }}
          action: "close"
